---
name: Math-Telephony-ErlangB
version: 1.0.0
author:
  - 'Flavio Poletti <flavio [at] polettix [dot] it>'
abstract: Erlang B calculations from Perl
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
  version: 0
provides:
  Math::Telephony::ErlangB:
    file: lib/Math/Telephony/ErlangB.pm
    version: 1.0.0
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
